{% set name = "splunk-opentelemetry" %}
{% set version = "2.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_') }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a76590faeceaf8dcfc8a261927de7d27794dd8570d61e79b9fb4f750bcce63b9

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  entry_points:
    - splunk-py-trace = splunk_otel.cmd.trace:run
    - splunk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run
    - splk-py-trace = splunk_otel.cmd.trace:run_deprecated
    - splk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run_deprecated

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - opentelemetry-api ==1.44.0
    - opentelemetry-sdk ==1.44.0
    - opentelemetry-instrumentation ==0.65b0
    - opentelemetry-instrumentation-system-metrics ==0.65b0
    - opentelemetry-semantic-conventions ==0.65b0
    - opentelemetry-propagator-b3 ==1.44.0
    - opentelemetry-exporter-otlp-proto-grpc ==1.44.0
    - opentelemetry-exporter-otlp-proto-http ==1.44.0
    - protobuf >=6.33.5
    - opentelemetry-instrumentation-logging ==0.65b0
    - opentelemetry-opamp-client ==0.3b0
    - wrapt >=2.2.2
  run_constrained:
    - secureapp-python-agent >=26.7.1

test:
  source_files:
    - tests
  imports:
    - splunk_otel
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/signalfx/splunk-otel-python
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM.
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/signalfx/splunk-otel-python
  dev_url: https://github.com/signalfx/splunk-otel-python

extra:
  recipe-maintainers:
    - Arishamays1
