{% set name = "splunk-opentelemetry" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/signalfx/splunk-otel-python/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 84fe14c6f9d71a2bae83c04beea2287bc41e78185c1bd6d1f6385640a953adc6

build:
  # entry_points:
  #   - splunk-py-trace = splunk_otel.cmd.trace:run
  #   - splunk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run
  #   - splk-py-trace = splunk_otel.cmd.trace:run_deprecated
  #   - splk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run_deprecated
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  number: 0
  skip: True # [py<38]

requirements:
  host:
    - python
    - poetry-core
    - pip
    - setuptools
    - wheel
  run:
    - python
    - cryptography >=2.0,<=43.0.1
    - protobuf >=4.23.0,<5.0.0
    - opentelemetry-api 1.26.0
    - opentelemetry-sdk 1.26.0
    - opentelemetry-instrumentation 0.47b0
    - opentelemetry-instrumentation-system-metrics 0.47b0
    - opentelemetry-semantic-conventions 0.47b0
    - opentelemetry-propagator-b3 1.26.0
    - opentelemetry-exporter-otlp-proto-grpc 1.26.0
    - opentelemetry-exporter-otlp-proto-http 1.26.0

test:
  imports:
    - splunk_otel.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/signalfx/splunk-otel-python
  summary: The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM.
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/signalfx/splunk-otel-python/tree/main/docs
  dev_url:

extra:
  recipe-maintainers:
    - Arishamays1
