{% set name = "splunk-opentelemetry" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name.replace('-', '_') }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3063382f7dacbec9d15394d37ec9c8bd157053900b74d48e9bcf7c98b112b434

build:
  entry_points:
    - splunk-py-trace = splunk_otel.cmd.trace:run
    - splunk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run
    - splk-py-trace = splunk_otel.cmd.trace:run_deprecated
    - splk-py-trace-bootstrap = splunk_otel.cmd.bootstrap:run_deprecated
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vvv
  number: 0
  skip: True  # [py<38]
  skip: True  # [s390x]

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - opentelemetry-api 1.30.0
    - opentelemetry-sdk 1.30.0
    - opentelemetry-instrumentation 0.51b0
    - opentelemetry-instrumentation-system-metrics 0.51b0
    - opentelemetry-semantic-conventions 0.51b0
    - opentelemetry-propagator-b3 1.30.0
    - opentelemetry-exporter-otlp-proto-grpc 1.30.0
    - opentelemetry-exporter-otlp-proto-http 1.30.0

test:
  imports:
    - splunk_otel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/signalfx/splunk-otel-python
  summary: The Splunk distribution of OpenTelemetry Python Instrumentation provides a Python agent that automatically instruments your Python application to capture and report distributed traces to SignalFx APM.
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  description: |
    This package provides entrypoints to configure OpenTelemetry.
  doc_url: https://github.com/signalfx/splunk-otel-python
  dev_url: https://github.com/signalfx/splunk-otel-python

extra:
  recipe-maintainers:
    - Arishamays1
